TP3BanquePoirierVermersch-war/src/java/managedBeans/ClientDetailsMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBeans;

import entities.Client;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import session.GestionnaireDeClient;

/**
 *
 * @author Manon
 */
@Named(value = "clientDetails")
@SessionScoped
public class ClientDetailsMB implements Serializable {
    private int idClient;
    private Client client;
    
    @EJB
    private GestionnaireDeClient gestionnaireDeClient;
    
    /**
     * Creates a new instance of ClientDetailsMB
     */
    public ClientDetailsMB() {
    }

    public int getIdClient() {
        return idClient;
    }

    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }
    
    public Client getDetails(){
        return client;
    }
    
    public String list(){
        System.out.println("###LIST###");
        return "ClientList";
    }
    
    public String update(){
        System.out.println("###UPDATE###");
        client = gestionnaireDeClient.updateClient(client);
        return "ClientList";
    }
    
    public String create(){
        client = new Client();
        System.out.println("###CREATE###");
        gestionnaireDeClient.creerClient(client);
        return "ClientList";
    }
    
    public void loadClient(){
        this.client = gestionnaireDeClient.getClient(idClient);
    }
}

TP3BanquePoirierVermersch-war/src/java/managedBeans/CompteBancaireDepotMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBeans;

import entities.CompteBancaire;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import session.GestionnaireDeCompteBancaire;

/**
 *
 * @author patrick
 */
@Named(value = "compteBancaireDepot")
@SessionScoped
public class CompteBancaireDepotMB implements Serializable {

    private int idCompte;
    private int montant;

    @EJB
    private GestionnaireDeCompteBancaire gestionnaireDeCompteBancaire;

    /**
     * Creates a new instance of CompteBancaireDepotMB
     */
    public CompteBancaireDepotMB() {
    }

    public List<CompteBancaire> getListeComptes() {
        return gestionnaireDeCompteBancaire.getAllComptes();
    }

    public int getCompte() {
        return this.idCompte;
    }

    public void setCompte(int idCompte) {
        this.idCompte = idCompte;
    }

    public int getMontant() {
        return this.montant;
    }

    public void setMontant(int montant) {
        this.montant = montant;
    }

    public void deposer() {
        gestionnaireDeCompteBancaire.deposer(getCompte(), getMontant());
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        try {
            context.redirect(context.getRequestContextPath()
                    + "/ClientListeComptes.xhtml");
        } catch (IOException ex) {
            Logger.getLogger(CompteBancaireDepotMB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

TP3BanquePoirierVermersch-war/src/java/managedBeans/CompteBancaireTransfertMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBeans;

import entities.CompteBancaire;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import session.GestionnaireDeCompteBancaire;

/**
 *
 * @author Manon
 */
@Named(value = "compteBancaireTransfertMB")
@SessionScoped
public class CompteBancaireTransfertMB implements Serializable {
    
    private int idCompteDebit;
    private int idCompteCredit;
    private int montant;
    
    @EJB
    private GestionnaireDeCompteBancaire gestionnaireDeCompteBancaire;

    /**
     * Creates a new instance of CompteBancaireTransfertMB
     */
    public CompteBancaireTransfertMB() {
    }
    
    public List<CompteBancaire> getListeComptesDebit(){
        return gestionnaireDeCompteBancaire.getAllComptes();
    }
    
    public List<CompteBancaire> getListeComptesCredit(){
        return gestionnaireDeCompteBancaire.getAllComptes();
    }
    
    public int getCompteDebit(){
        return this.idCompteDebit;
    }
    
    public void setCompteDebit(int idCompteDebit){
        this.idCompteDebit = idCompteDebit;
    }
    
    public int getCompteCredit(){
        return this.idCompteCredit;
    }
    
    public void setCompteCredit(int idCompteCredit){
        this.idCompteCredit = idCompteCredit;
    }
    
    public int getMontant(){
        return this.montant;
    }
    
    public void setMontant(int montant){
        this.montant = montant;
    }
    
    public void transferer(){
        gestionnaireDeCompteBancaire.transferer(getCompteDebit(), getCompteCredit(), getMontant());
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        try {
            context.redirect(context.getRequestContextPath() + "/ClientListeComptes.xhtml");
        } catch (IOException ex){
            Logger.getLogger(CompteBancaireTransfertMB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

TP3BanquePoirierVermersch-war/web/client/ClientDepot.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Dépôt d'argent</title>
    </h:head>
    <h:body>
        <ui:composition template="../templates/template_client.xhtml">
            <ui:define name="title">Dépôt d'argent</ui:define>
            <ui:define name="toolbar"></ui:define>
            <ui:define name="content">
                <f:view>
                    <h:form>
                        <div class="col-md-8 offset-2">
                            <div class="form-group">
                                <p:outputLabel for="depot-compte" value="Compte : " />
                                <h:selectOneMenu id="depot-compte" styleClass="form-control"  value="#{compteBancaireDepot.compte}" style="width: 25%; min-width: 300px;">
                                    <f:selectItem itemLabel="Choisir un compte" itemValue="" noSelectionOption="true"/>
                                    <c:forEach var="item" items="#{compteBancaireDepot.listeComptes}">
                                        <f:selectItem itemLabel="#{item.nom} : #{item.solde}" itemValue="#{item.id}" />
                                    </c:forEach>
                                </h:selectOneMenu>
                            </div>
                            <div class="form-group">
                                <h:outputLabel value="Montant :" for="depot-montant" />
                                <h:inputText id="depot-montant" styleClass="form-control col-md-8" value="#{compteBancaireDepot.montant}" title="montant" />
                            </div>
                            <a class="btn btn-outline-secondary" style="margin-right: 2%;"  href="/TP3BanquePoirierVermersch-war/client/ClientListeComptes.xhtml">Annuler</a>
                            <h:commandButton id="save" styleClass="btn btn-success" value="Faire un dépôt" action="#{compteBancaireDepot.deposer}"/>
                        </div>
                    </h:form>
                </f:view>

            </ui:define>
        </ui:composition>
    </h:body>
</html>

TP3BanquePoirierVermersch-war/web/client/ClientDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      template="/template_presentation.xhtml">
    
    <f:metadata>
        <f:viewParam name="idCompte" value="#{compteBancaireDetails.idCompte}" required="true"/>
        <f:viewAction action="#{compteBancaireDetails.loadCompteBancaire}"/>
    </f:metadata>
    
    <h:head>
        <title>Liste des comptes bancaires</title>
    </h:head>
    <h:body>
        <ui:composition template="../templates/template_client.xhtml">
            <ui:define name="title">Details du compte #{compteBancaireDetails.details.nom}</ui:define>
            <ui:define name="toolbar"></ui:define>
            <ui:define name="content">
                <h:form>
                    <f:view>
                        <div class="col-md-8 offset-2">
                            <div class="form-group">
                                <h:outputLabel value="Numéro du compte :" for="id" />
                                <h:inputText id="id" styleClass="form-control col-md-8" value="#{compteBancaireDetails.details.id}" title="Id" readonly="true"/>
                            </div>
                            <div class="form-group">
                                <h:outputLabel value="Libellé du compte :" for="nom" />
                                <h:inputText id="nom" styleClass="form-control col-md-8" value="#{compteBancaireDetails.details.nom}" title="Nom" readonly="true"/>
                            </div>
                            <div class="form-group">
                                <h:outputLabel value="Solde du compte :" for="solde" />
                                <h:inputText id="solde" styleClass="form-control col-md-8" value="#{compteBancaireDetails.details.solde}" title="Solde" readonly="true"/>
                            </div>
                            <a class="btn btn-outline-secondary" href="/TP3BanquePoirierVermersch-war/client/ClientListeComptes.xhtml">Retour</a>
                        </div>
                    </f:view>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TP3BanquePoirierVermersch-war/web/client/ClientListeComptes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      template="/template_presentation.xhtml">
    <h:head>
        <title>List des comptes bancaires</title>
    </h:head>
    <h:body>
        <ui:composition template="../templates/template_client.xhtml">
            <ui:define name="title">Liste des comptes bancaires</ui:define>
            <ui:define name="toolbar"></ui:define>
            <ui:define name="content">
                <f:view>
                    <div class="table-responsive">
                        <h:form>
                            <p:dataTable value="#{compteBancaireMB.compteBancaireList}" var="item">
                                <p:column sortBy="#{item.id}" styleClass="text-center">
                                    <f:facet name="header">
                                        <h:outputText value="Numéro de compte"/>
                                    </f:facet>
                                    <h:outputText value="#{item.id}"/>
                                </p:column>
                                <p:column sortBy="#{item.nom}" styleClass="text-center">
                                    <f:facet name="header">
                                        <h:outputText value="Libellé"/>
                                    </f:facet>
                                    <h:outputText value="#{item.nom}"/>
                                </p:column>
                                <p:column sortBy="#{item.solde}" styleClass="text-center">
                                    <f:facet name="header">
                                        <h:outputText value="Solde"/>
                                    </f:facet>
                                    <h:outputText value="#{item.solde}"/>
                                </p:column>
                                <p:column styleClass="text-center">
                                    <f:facet name="header">
                                        <h:outputText value="Voir plus"/>
                                    </f:facet>
                                    <h:link outcome="#{compteBancaireMB.showDetails(item.id)}"><span data-feather="zoom-in"></span> Voir les détails </h:link>
                                </p:column>
                            </p:dataTable>
                        </h:form>
                    </div>
                    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
                    <script>
                        feather.replace()
                    </script>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TP3BanquePoirierVermersch-war/web/client/ClientRetrait.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Retrait d'argent</title>
    </h:head>
    <h:body>
        <ui:composition template="../templates/template_client.xhtml">
            <ui:define name="title">Retrait d'argent</ui:define>
            <ui:define name="toolbar"></ui:define>
            <ui:define name="content">
                <h:form>
                    <div class="col-md-8 offset-2">
                        <div class="form-group">
                            <h:outputLabel value="Compte :" for="retrait-compte"/>
                            <h:selectOneMenu id="retrait-compte" styleClass="form-control" value="#{compteBancaireRetraitMB.compte}" style="width: 300px">
                                <f:selectItem itemLabel="Choisir un compte" itemValue="" noSelectionOption="true"/>
                                <c:forEach var="item" items="#{compteBancaireRetraitMB.listeComptes}">
                                    <f:selectItem itemLabel="#{item.nom} : #{item.solde}" itemValue="#{item.id}"/>
                                </c:forEach>
                            </h:selectOneMenu>
                        </div>
                        <div class="form-group">
                            <h:outputLabel value="Montant :" for="retrait-montant" />
                            <h:inputText id="retrait-montant" styleClass="form-control col-md-8" value="#{compteBancaireRetraitMB.montant}" title="Montant" />
                        </div>
                        <h:commandButton id="back" value="Annuler" styleClass="btn btn-outline-secondary" style="margin-right: 2%;" action="#{compteBancaireDetails.list}"/>
                        <h:commandButton id="update" value="Confirmer" styleClass="btn btn-success" action="#{compteBancaireRetraitMB.retirer}"/>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TP3BanquePoirierVermersch-war/web/client/ClientTransfert.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Transfert d'argent</title>
    </h:head>
    <h:body>
        <ui:composition template="../templates/template_client.xhtml">
            <ui:define name="title">Transfert d'argent</ui:define>
            <ui:define name="toolbar"></ui:define>
            <ui:define name="content">
                <f:view>
                    <h:form>
                        <div class="col-md-8 offset-2">
                            <div class="form-group">
                                <p:outputLabel for="transfert-debit" value="Compte à débiter : "/>
                                <h:selectOneMenu id="transfert-debit" styleClass="form-control" value="#{compteBancaireTransfertMB.compteDebit}" style="width:300px">
                                    <f:selectItem itemLabel="Choisir un compte" itemValue="" noSelectionOption="true"/>
                                    <c:forEach var="item" items="#{compteBancaireTransfertMB.listeComptesDebit}">
                                        <f:selectItem itemLabel="#{item.nom} : #{item.solde}€" itemValue="#{item.id}"/>
                                    </c:forEach>
                                </h:selectOneMenu>
                            </div>
                            <div class="form-group">
                                <p:outputLabel for="transfert-credit" value="Compte à créditer : "/>
                                <h:selectOneMenu id="transfert-credit" styleClass="form-control" value="#{compteBancaireTransfertMB.compteCredit}" style="width:300px">
                                    <f:selectItem itemLabel="Choisir un compte" itemValue="" noSelectionOption="true"/>
                                    <c:forEach var="item" items="#{compteBancaireTransfertMB.listeComptesCredit}">
                                        <f:selectItem itemLabel="#{item.nom} : #{item.solde}" itemValue="#{item.id}"/>
                                    </c:forEach>
                                </h:selectOneMenu>
                            </div>
                            <div class="form-group">
                                <h:outputLabel value="Montant :" for="transfert-montant"/>
                                <h:inputText styleClass="form-control col-md-8" id="trafert-montant" value="#{compteBancaireTransfertMB.montant}" title="montant"/>
                            </div>
                            <a class="btn btn-outline-secondary" style="margin-right: 2%;"  href="/TP3BanquePoirierVermersch-war/client/ClientListeComptes.xhtml">Annuler</a>
                            <h:commandButton id="save" styleClass="btn btn-success" value="Faire le transfert d'argent" action="#{compteBancaireTransfertMB.transferer}"/>
                        </div>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>